name       : kdepim-runtime
version    : 20.12.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kdepim-runtime-20.12.0.tar.xz : 6dd4cd1328aeb2699a51abf41056b7bb009104803a3f2cf70fc4966b21344b01
homepage   : https://community.kde.org/PIM
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Runtime components for Akonadi
description: |
    Contains the Akonadi resources from kdepim which can be used without the applications in kdepim.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libcurl)
    - pkgconfig(libsasl2)
    - pkgconfig(qca2-qt5)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - grantleetheme-devel
    - kalarmcal-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdav-devel
    - kdoctools-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - libkgapi-devel
    - libkolabxml-devel
    - pimcommon-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
