name       : kdepim-runtime
version    : 19.08.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kdepim-runtime-19.08.3.tar.xz : 2673967456b7eacbd69ca678761e479bfa65a0ec6455c86b3a83c76d766a71ea
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Runtime components for Akonadi
description: |
    Contains the Akonadi resources from kdepim which can be used without the applications in kdepim.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libcurl)
    - pkgconfig(libsasl2)
    - pkgconfig(qca2-qt5)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - kalarmcal-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdav-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - libkgapi-devel
    - libkolabxml-devel
    - pimcommon-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
