name       : kdepim-runtime
version    : 18.12.3
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kdepim-runtime-18.12.3.tar.xz : f3a5da19bb0f60e148d071cf07fd9fd4e6ea116f6125567c767c03b98ea844c3
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Runtime components for Akonadi
description: |
    Contains the Akonadi resources from kdepim which can be used without the applications in kdepim.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libcurl)
    - pkgconfig(libsasl2)
    - pkgconfig(qca2-qt5)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - kalarmcal-devel
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kdav-devel
    - kdelibs4support-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - libkgapi-devel
    - libkolabxml-devel
    - pimcommon-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
