name       : kdepim-runtime
version    : 18.04.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kdepim-runtime-18.04.2.tar.xz : d7a1fc6e5a62649915e9e2580d4a27e0a9a5ba0e4a570ee637c1e6266afb5da3
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Runtime components for Akonadi
description: |
    Contains the Akonadi resources from kdepim which can be used without the applications in kdepim.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - kalarmcal-devel
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kdav-devel
    - kdelibs4support-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - libkgapi-devel
    - libkolabxml-devel
    - pimcommon-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
