name       : kdepim-runtime
version    : 19.12.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kdepim-runtime-19.12.2.tar.xz : f3efe4627a5c73e0072264250dd3ec910c732c0f4c87eaab7593eb239a164129
homepage   : https://community.kde.org/PIM
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Runtime components for Akonadi
description: |
    Contains the Akonadi resources from kdepim which can be used without the applications in kdepim.
builddeps  :
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libcurl)
    - pkgconfig(libsasl2)
    - pkgconfig(qca2-qt5)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - extra-cmake-modules
    - kalarmcal-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdav-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - libkgapi-devel
    - libkolabxml-devel
    - pimcommon-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
